name: ansible-lint
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint Ansible Playbook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@5fac056c45595896c973fbde871f01f6cb14d74c # v26

      - name: Upload Sarif file
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4
        with:
          sarif_file: ansible-lint.sarif
        if: always()
