name: Renovate

on:
  push:
    paths:
      - ".github/workflows/renovate.yml"
      - ".github/renovate.json"
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/renovate.yml"
      - ".github/renovate.json"
    branches:
      - main
  schedule:
    - cron: "0 2 * * *" # 2am daily
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run Renovate
        uses: renovatebot/github-action@02f4fdeb479bbb229caa7ad82cb5e691c07e80b3 # v41.0.14
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.app-token.outputs.token }}
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL)$"
        env:
          LOG_LEVEL: info
          RENOVATE_REPOSITORIES: 'micxer/ansible-role-docker-compose-homestack'
          RENOVATE_AUTODISCOVER: false
          RENOVATE_AUTOMERGE: false
          RENOVATE_PLATFORM: github
          RENOVATE_DETECT_HOST_RULES_FROM_ENV: true